/**
 * @file ads1115.h
 * @brief Driver đơn giản cho ADS1115 (16-bit ADC) trên ESP32
 * @author Manhquan (Generated by Gemini)
 */

#ifndef ADS1115_H
#define ADS1115_H

#ifdef __cplusplus
extern "C" {
#endif

#include "esp_err.h"
#include "driver/i2c.h"

// --- I2C Config ---
#define ADS1115_ADDR_GND    0x48    // Địa chỉ khi chân ADDR nối GND
#define ADS1115_ADDR_VDD    0x49    // Địa chỉ khi chân ADDR nối VDD

// --- Programmable Gain Amplifier (PGA) ---
typedef enum {
    ADS1115_GAIN_6_144V = 0x0000,  // 2/3x gain +/- 6.144V  (default)
    ADS1115_GAIN_4_096V = 0x0200,  // 1x gain   +/- 4.096V  (Tốt cho 3.3V Logic)
    ADS1115_GAIN_2_048V = 0x0400,  // 2x gain   +/- 2.048V
    ADS1115_GAIN_1_024V = 0x0600,  // 4x gain   +/- 1.024V
    ADS1115_GAIN_0_512V = 0x0800,  // 8x gain   +/- 0.512V
    ADS1115_GAIN_0_256V = 0x0A00   // 16x gain  +/- 0.256V
} ads_gain_t;

// --- Data Rate (Samples per Second) ---
typedef enum {
    ADS1115_DR_8SPS    = 0x0000,
    ADS1115_DR_128SPS  = 0x0080,   // Default
    ADS1115_DR_250SPS  = 0x00A0,
    ADS1115_DR_475SPS  = 0x00C0,
    ADS1115_DR_860SPS  = 0x00E0    // Tốt nhất cho ECG mượt mà
} ads_sps_t;

// --- Multiplexer (Input Channel) ---
typedef enum {
    ADS1115_MUX_DIFF_0_1 = 0x0000, // So sánh A0 và A1
    ADS1115_MUX_SINGLE_0 = 0x4000, // Đọc riêng chân A0 (Cho ECG AD8232)
    ADS1115_MUX_SINGLE_1 = 0x5000, // Đọc riêng chân A1
    ADS1115_MUX_SINGLE_2 = 0x6000, // Đọc riêng chân A2
    ADS1115_MUX_SINGLE_3 = 0x7000  // Đọc riêng chân A3
} ads_mux_t;

/**
 * @brief Khởi tạo I2C Driver cho ADS1115
 * @param i2c_num Cổng I2C (I2C_NUM_0 hoặc I2C_NUM_1)
 * @param sda_pin GPIO cho SDA
 * @param scl_pin GPIO cho SCL
 * @return ESP_OK nếu thành công
 */
esp_err_t ads1115_init_i2c(i2c_port_t i2c_num, int sda_pin, int scl_pin);

/**
 * @brief Đọc giá trị ADC từ 1 kênh cụ thể (Single-ended)
 * Hàm này sẽ cấu hình config, đợi chuyển đổi xong và đọc kết quả.
 * @param mux Kênh cần đọc (Ví dụ: ADS1115_MUX_SINGLE_0)
 * @param gain Độ lợi (Ví dụ: ADS1115_GAIN_4_096V)
 * @param sps Tốc độ mẫu (Ví dụ: ADS1115_DR_860SPS)
 * @return Giá trị 16-bit có dấu (ADC Value)
 */
int16_t ads1115_get_raw(ads_mux_t mux, ads_gain_t gain, ads_sps_t sps);

#ifdef __cplusplus
}
#endif

#endif // ADS1115_H